minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@replit/*'
  - stripe-replit-sync

packages:
  - ../sdk

onlyBuiltDependencies:
  - esbuild
  - protobufjs

allowBuilds:
  esbuild: true
  protobufjs: true
